config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"

  devise_for :users

  resources :users

  resources :events



  #get 'events/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :event_participe

  belongs_to :participant, class_name: "User"
  belongs_to :event

  validates :stripe_customer_id, uniqueness:true

  def event_participe #un utilisateur a participer a un evenement
    UserMailer.event_participe(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :participants, through: :attendances

  validates :start_date, presence: true, if: :is_valid_date
  validates :duration, presence: true, numericality: {greater_than: 0}, if: :duration_test
  validates :title, presence: true, length: {in: 5..140 }
  validates :description, presence: true, length: {in: 20..500 }
  validates :price, presence: true
  validates_inclusion_of :price, in: 1..1000, message:'Le prix doit être de 1 à 1000'
  validates :location, presence: true

  def is_valid_date
    if start_date.nil? || DateTime.now > start_date
      errors.add(:start_date, :not_date ,{message: 'Un evenement doits être dans le futur'})
    end
  end
  def duration_test
    if duration.nil? || (duration % 5 != 0)
      errors.add(:duration, :not_pos5, {message:'Le durée doits être positif et multiple de 5'})
    end
  end

  def end_date
    self.start_date + (self.duration).minute
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :user_created_compte

  has_many :admin_event, foreign_key: 'admin_id', class_name: 'Event'
  has_many :participant_event, foreign_key: 'participant_id', class_name: 'Event'
  has_many :attendances
  has_many :events, through: :attendances

  validates :first_name, presence: true, length: {minimum: 3 }
  validates :last_name, presence: true, length: {minimum: 3 }
  validates :description, presence: true, length: {in: 20..500 }

#a chaque fois qu'un user est crée
#en lui envoi un email de bienvenue
  def user_created_compte
    UserMailer.user_created_compte(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, only: [:new,:create]
  def new
    @event = Event.new
  end
  def show
    @event = Event.find(params[:id])
    @listes = @event.participants.length
  end

  def create
    @event = Event.new(start_date:params[:start_date],duration:params[:duration],title:params[:title],description:params[:description],price:params[:price],location:params[:location],admin_id:current_user.id)
    if @event.save
      redirect_to event_path(@event.id)
    else
      render "new"
    end
  end

  def index
    @events = Event.all
  end

  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def show
    if is_acces(params[:id])
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    #current_user
  end

  private

  def is_acces(id)
    if current_user.id == id
      returne true
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1 class="jumbotron-heading">Cree un evenement</h1>
<p class="lead text-muted">Pour cree un evenent vous pouvez cliquer sur le lien ci-dessous</p>

app/views/events/index.html.erb
<% one = @events.length / 3%>
<% two = @events.length % 3%>
<% index = 0 %>
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Cree un evenement</h1>
      <p class="lead text-muted">Pour cree un evenent vous pouvez cliquer sur le lien ci-dessous</p>
      <p>
        <a href="<%=new_event_path%>" class="btn btn-primary my-2">Go</a>
      </p>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% one.times do |i| %>

        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h2>Titre : <%=@events[index].title%></h2>
              <ul>
                <li>Debut : <%=@events[index].start_date%></li>
                <li>Durée : <%=@events[index].duration%> mn</li>
                <li>Prix : <%=@events[index].price%> €</li>
                <li>Lieu : <%=@events[index].location%></li>
                <li>Crée par : <%=@events[index].admin.first_name%> <%=@events[index].admin.last_name%></li>
              </ul>
              <p class="card-text">Description : <%=@events[index].description%></p>
              <a href="<%=event_path(@events[index].id)%>"><button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              <hr class="my-4">
              <div class="d-flex justify-content-between align-items-center">
                <div class="card-body">
                  <small class="text-muted">Crée le : <%=@events[index].created_at%></small><br/>
                  <small class="text-muted">Dernier mise à jour : <%=@events[index].updated_at%></small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%index+=1%>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h2>Titre : <%=@events[index].title%></h2>
              <ul>
                <li>Debut : <%=@events[index].start_date%></li>
                <li>Durée : <%=@events[index].duration%> mn</li>
                <li>Prix : <%=@events[index].price%> €</li>
                <li>Lieu : <%=@events[index].location%></li>
                <li>Crée par : <%=@events[index].admin.first_name%> <%=@events[index].admin.last_name%></li>
              </ul>
              <p class="card-text">Description : <%=@events[index].description%></p>
              <a href="<%=event_path(@events[index].id)%>"><button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              <hr class="my-4">
              <div class="d-flex justify-content-between align-items-center">
                <div class="card-body">
                  <small class="text-muted">Crée le : <%=@events[index].created_at%></small><br/>
                  <small class="text-muted">Dernier mise à jour : <%=@events[index].updated_at%></small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%index+=1%>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h2>Titre : <%=@events[index].title%></h2>
              <ul>
                <li>Debut : <%=@events[index].start_date%></li>
                <li>Durée : <%=@events[index].duration%> mn</li>
                <li>Prix : <%=@events[index].price%> €</li>
                <li>Lieu : <%=@events[index].location%></li>
                <li>Crée par : <%=@events[index].admin.first_name%> <%=@events[index].admin.last_name%></li>
              </ul>
              <p class="card-text">Description : <%=@events[index].description%></p>
              <a href="<%=event_path(@events[index].id)%>"><button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              <hr class="my-4">
              <div class="d-flex justify-content-between align-items-center">
                <div class="card-body">
                  <small class="text-muted">Crée le : <%=@events[index].created_at%></small><br/>
                  <small class="text-muted">Dernier mise à jour : <%=@events[index].updated_at%></small>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%index+=1%>
        <%end%>
        <%two.times do |i|%>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h2><%=@events[index].title%></h2>
              <ul>
                <li>Debut : <%=@events[index].start_date%></li>
                <li>Durée : <%=@events[index].duration%> mn</li>
                <li>Prix : <%=@events[index].price%> €</li>
                <li>Lieu : <%=@events[index].location%></li>
                <li>Crée par : <%=@events[index].admin.first_name%> <%=@events[index].admin.last_name%></li>
              </ul>
              <p class="card-text">Description : <%=@events[index].description%></p>
              <a href="<%=event_path(@events[index].id)%>"><button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              <hr class="my-4">
              <div class="d-flex justify-content-between align-items-center">
                <div class="card" style="width: 18rem;">
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><small>Crée le : <%=@events[index].created_at%></small></li>
                    <li class="list-group-item"><small>Dernier mise à jour : <%=@events[index].updated_at%></small></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
          <%index+=1%>
        <%end%>
      </div>
    </div>
  </div>
</main>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>

app/views/events/new.html.erb
<%= form_tag url_for(controller:'events', action:'create'), method:'post' do %>
  <div class="form-row">
    <div class="form-group form-group col-md-6">
      <label>Titre</<label>
        <%=text_field_tag 'title', nil, class:'form-control'%>
    </div>
    <div class="form-group form-group col-md-6">
        <label>Location</label>
        <%=text_field_tag 'location', nil,class:'form-control'%>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label>Date de debut : </<label>
      <%=date_field_tag 'start_date', '01/01/2014', class: 'form-control'  %>
    </div>
    <div class="form-group col-md-4">
        <label>Duration</label>
        <%=number_field_tag 'duration', nil,class:'form-control'%>
    </div>
    <div class="form-group col-md-4">
        <label>Price</label>
        <%=number_field_tag 'price', nil,class:'form-control'%>
    </div>
  </div>
  <div class="form-group">
      <label>Description</label>
      <%=text_area_tag 'description', nil,class:'form-control'%>
  </div>
  <div class="form-group row">
    <div class="col-sm-5">
      <%= submit_tag "Créer l'evenement",class:"btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
<%end%>

<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="jumbotron">
  <center><h1 class="display-4"><%=@event.title%></h1>
    <p>Debut : <%=@event.start_date%><br>
      Durée : <%=@event.duration%> mn<br>
      Prix : <%=@event.price%> €<br>
      Lieu : <%=@event.location%><br>
      Crée par : <%=@event.admin.first_name%> <%=@event.admin.last_name%></p>
  </center>
  <hr class="my-4">
  <p class="lead"><%=@event.description%></p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

<p><%= @listes%> personnes sont inscrit a cette evenement</p>
<h3>Fin de l'evenement : <%=@event.end_date%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Accueil</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%=new_event_path%>">Cree un evenement<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%if user_signed_in?%>
                <a class="dropdown-item" href="<%=user_path(current_user.id)%>">Mon profil</a>
                <%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
              <%else%>
                <a class="dropdown-item" href="<%=new_user_registration_path%>">S'inscrire</a>
                <a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a>
              <%end%>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>


    </body>
</html>

app/views/users/show.html.erb
<h1><%=@user.first_name%> <%=@user.last_name%></h1>
<p>Name : <%=@user.first_name%> <%=@user.last_name%></p>
<p>Email : <%=@user.email%></p>
<p>Description : <br><%=@user.description%></p>
<a href = "<%=edit_user_registration_path%>">Editer mon profil</a>

<% if current_user.id == @user.id %>
  <div class="jumbotron">
    <center>
      <h1 class="display-4"></h1>
    </center>
    <hr class="my-4">
    <p class="lead">gsdfgsd</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </div>
<% end %>